package com.psy.entity;

// Generated 2015-4-20 13:45:41 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher")
public class Teacher implements java.io.Serializable {

	private Integer teachId;
	private String name;
	private String password;
	private String sex;
	private String nation;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "teach_Id", unique = true, nullable = false)
	public Integer getTeachId() {
		return this.teachId;
	}

	public void setTeachId(Integer teachId) {
		this.teachId = teachId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "sex")
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "nation")
	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

}
