package com.psy.entity;

// Generated 2015-7-22 10:31:35 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book")
public class Book implements java.io.Serializable {

	private String bookId;
	private String bookName;
	private String subTitle;
	private String author;
	private String translator;
	private String drawor;
	private String editor;
	private String inputer;
	private String type;
	private String recommend;
	private String subject;
	private String degree;
	private String startAge;
	private String endAge;
	private String country;
	private String space;
	private String grade;
	private String isbn10;
	private String isbn13;
	private String nums;
	private String pages;
	private String authorIntro;
	private String dbTags;
	private String schoolTags;
	private String publisher;
	private String pubdate;
	private String summary;
	private String price;
	private String content;
	private String images;
	private String smallImages;
	private String largeImages;
	private String mediumImages;
	private String background;
	private String createTime;

	public Book() {
	}

	public Book(String bookName, String subTitle, String author, String translator,
			String drawor, String editor, String inputer, String type, String recommend,
			String subject, String degree, String startAge, String endAge,
			String country, String space, String grade, String isbn10,
			String isbn13, String nums, String pages, String authorIntro,
			String dbTags, String schoolTags, String publisher, String pubdate,
			String summary, String price, String content, String images,
			String smallImages, String largeImages, String mediumImages,
			String background, String createTime) {
		this.bookName = bookName;
		this.subTitle = subTitle;
		this.author = author;
		this.translator = translator;
		this.drawor = drawor;
		this.editor = editor;
		this.inputer = inputer;
		this.type = type;
		this.recommend = recommend;
		this.subject = subject;
		this.degree = degree;
		this.startAge = startAge;
		this.endAge = endAge;
		this.country = country;
		this.space = space;
		this.grade = grade;
		this.isbn10 = isbn10;
		this.isbn13 = isbn13;
		this.nums = nums;
		this.pages = pages;
		this.authorIntro = authorIntro;
		this.dbTags = dbTags;
		this.schoolTags = schoolTags;
		this.publisher = publisher;
		this.pubdate = pubdate;
		this.summary = summary;
		this.price = price;
		this.content = content;
		this.images = images;
		this.smallImages = smallImages;
		this.largeImages = largeImages;
		this.mediumImages = mediumImages;
		this.background = background;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "book_id", unique = true, nullable = false)
	public String getBookId() {
		return this.bookId;
	}

	public void setBookId(String bookId) {
		this.bookId = bookId;
	}
	
	@Column(name = "book_name")
	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}
	
	@Column(name = "sub_title")
	public String getSubTitle() {
		return subTitle;
	}

	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

	@Column(name = "author")
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "translator")
	public String getTranslator() {
		return this.translator;
	}

	public void setTranslator(String translator) {
		this.translator = translator;
	}

	@Column(name = "drawor")
	public String getDrawor() {
		return this.drawor;
	}

	public void setDrawor(String drawor) {
		this.drawor = drawor;
	}

	@Column(name = "editor")
	public String getEditor() {
		return this.editor;
	}

	public void setEditor(String editor) {
		this.editor = editor;
	}

	@Column(name = "inputer")
	public String getInputer() {
		return inputer;
	}

	public void setInputer(String inputer) {
		this.inputer = inputer;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "recommend")
	public String getRecommend() {
		return this.recommend;
	}

	public void setRecommend(String recommend) {
		this.recommend = recommend;
	}

	@Column(name = "subject")
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "degree")
	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	@Column(name = "start_age")
	public String getStartAge() {
		return this.startAge;
	}

	public void setStartAge(String startAge) {
		this.startAge = startAge;
	}

	@Column(name = "end_age")
	public String getEndAge() {
		return this.endAge;
	}

	public void setEndAge(String endAge) {
		this.endAge = endAge;
	}

	@Column(name = "country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "space")
	public String getSpace() {
		return this.space;
	}

	public void setSpace(String space) {
		this.space = space;
	}

	@Column(name = "grade")
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@Column(name = "isbn10")
	public String getIsbn10() {
		return this.isbn10;
	}

	public void setIsbn10(String isbn10) {
		this.isbn10 = isbn10;
	}

	@Column(name = "isbn13")
	public String getIsbn13() {
		return this.isbn13;
	}

	public void setIsbn13(String isbn13) {
		this.isbn13 = isbn13;
	}

	@Column(name = "nums", length = 60)
	public String getNums() {
		return this.nums;
	}

	public void setNums(String nums) {
		this.nums = nums;
	}

	@Column(name = "pages", length = 30)
	public String getPages() {
		return this.pages;
	}

	public void setPages(String pages) {
		this.pages = pages;
	}

	@Column(name = "author_intro", length = 4000)
	public String getAuthorIntro() {
		return this.authorIntro;
	}

	public void setAuthorIntro(String authorIntro) {
		this.authorIntro = authorIntro;
	}

	@Column(name = "db_tags", length = 3000)
	public String getDbTags() {
		return this.dbTags;
	}

	public void setDbTags(String dbTags) {
		this.dbTags = dbTags;
	}

	@Column(name = "school_tags", length = 3000)
	public String getSchoolTags() {
		return this.schoolTags;
	}

	public void setSchoolTags(String schoolTags) {
		this.schoolTags = schoolTags;
	}

	@Column(name = "publisher")
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "pubdate", length = 30)
	public String getPubdate() {
		return this.pubdate;
	}

	public void setPubdate(String pubdate) {
		this.pubdate = pubdate;
	}

	@Column(name = "summary", length = 4000)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "price", length = 30)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "images")
	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}

	@Column(name = "small_images")
	public String getSmallImages() {
		return this.smallImages;
	}

	public void setSmallImages(String smallImages) {
		this.smallImages = smallImages;
	}

	@Column(name = "large_images")
	public String getLargeImages() {
		return this.largeImages;
	}

	public void setLargeImages(String largeImages) {
		this.largeImages = largeImages;
	}

	@Column(name = "medium_images")
	public String getMediumImages() {
		return this.mediumImages;
	}

	public void setMediumImages(String mediumImages) {
		this.mediumImages = mediumImages;
	}

	@Column(name = "background")
	public String getBackground() {
		return this.background;
	}

	public void setBackground(String background) {
		this.background = background;
	}

	@Column(name = "create_time", length = 30)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
