package com.psy.entity;

// Generated 2015-6-9 10:27:23 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book")
public class Book implements java.io.Serializable {

	private String bookId;
	private String bookName;
	private String author;
	private String type;
	private String recommend;
	private String subject;
	private String grade;
	private String isbn10;
	private String isbn13;
	private String pages;
	private String authorIntro;
	private String translator;
	private String commonTags;
	private String publisher;
	private String pubdate;
	private String summary;
	private String price;
	private byte[] content;
	private String images;
	private String smallImages;
	private String largeImages;
	private String mediumImages;
	private String background;
	private String createTime;

	public Book() {
	}

	public Book(String bookName, String author, String type, String recommend,
			String subject, String grade, String isbn10, String isbn13,
			String pages, String authorIntro, String translator,
			String commonTags, String publisher, String pubdate,
			String summary, String price, byte[] content, String images, String smallImages,
			String largeImages, String mediumImages, String background, String createTime) {
		this.bookName = bookName;
		this.author = author;
		this.type = type;
		this.recommend = recommend;
		this.subject = subject;
		this.grade = grade;
		this.isbn10 = isbn10;
		this.isbn13 = isbn13;
		this.pages = pages;
		this.authorIntro = authorIntro;
		this.translator = translator;
		this.commonTags = commonTags;
		this.publisher = publisher;
		this.pubdate = pubdate;
		this.summary = summary;
		this.price = price;
		this.content = content;
		this.images = images;
		this.smallImages = smallImages;
		this.largeImages = largeImages;
		this.mediumImages = mediumImages;
		this.background = background;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "book_id", unique = true, nullable = false)
	public String getBookId() {
		return this.bookId;
	}

	public void setBookId(String bookId) {
		this.bookId = bookId;
	}

	@Column(name = "book_name")
	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	@Column(name = "author")
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "recommend")
	public String getRecommend() {
		return this.recommend;
	}

	public void setRecommend(String recommend) {
		this.recommend = recommend;
	}

	@Column(name = "subject")
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "grade")
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@Column(name = "isbn10")
	public String getIsbn10() {
		return this.isbn10;
	}

	public void setIsbn10(String isbn10) {
		this.isbn10 = isbn10;
	}

	@Column(name = "isbn13")
	public String getIsbn13() {
		return this.isbn13;
	}

	public void setIsbn13(String isbn13) {
		this.isbn13 = isbn13;
	}

	@Column(name = "pages", length = 30)
	public String getPages() {
		return this.pages;
	}

	public void setPages(String pages) {
		this.pages = pages;
	}

	@Column(name = "author_intro", length = 4000)
	public String getAuthorIntro() {
		return this.authorIntro;
	}

	public void setAuthorIntro(String authorIntro) {
		this.authorIntro = authorIntro;
	}

	@Column(name = "translator")
	public String getTranslator() {
		return this.translator;
	}

	public void setTranslator(String translator) {
		this.translator = translator;
	}

	@Column(name = "common_tags", length = 3000)
	public String getCommonTags() {
		return this.commonTags;
	}

	public void setCommonTags(String commonTags) {
		this.commonTags = commonTags;
	}

	@Column(name = "publisher")
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "pubdate", length = 30)
	public String getPubdate() {
		return this.pubdate;
	}

	public void setPubdate(String pubdate) {
		this.pubdate = pubdate;
	}

	@Column(name = "summary", length = 4000)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "price", length = 30)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "content")
	public byte[] getContent() {
		return this.content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}
	
	@Column(name = "images")
	public String getImages() {
		return images;
	}

	public void setImages(String images) {
		this.images = images;
	}

	@Column(name = "small_images")
	public String getSmallImages() {
		return this.smallImages;
	}

	public void setSmallImages(String smallImages) {
		this.smallImages = smallImages;
	}

	@Column(name = "large_images")
	public String getLargeImages() {
		return this.largeImages;
	}

	public void setLargeImages(String largeImages) {
		this.largeImages = largeImages;
	}

	@Column(name = "medium_images")
	public String getMediumImages() {
		return this.mediumImages;
	}

	public void setMediumImages(String mediumImages) {
		this.mediumImages = mediumImages;
	}

	@Column(name = "background")
	public String getBackground() {
		return background;
	}

	public void setBackground(String background) {
		this.background = background;
	}

	@Column(name = "create_time", length = 30)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
