package com.psy.entity;

// Generated 2015-7-22 10:55:23 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question")
public class Question implements java.io.Serializable {

	private String questionId;
	private String bookId;
	private String createTime;
	private String status;
	private String content;
	private String optionConfig;
	private String ansVal;
	private String questionType;
	private String timeOut;
	private String remark;

	public Question() {
	}

	public Question(String bookId, String createTime, String status, String content,
			String optionConfig, String ansVal, String questionType,
			String timeOut, String remark) {
		this.bookId = bookId;
		this.createTime = createTime;
		this.status = status;
		this.content = content;
		this.optionConfig = optionConfig;
		this.ansVal = ansVal;
		this.questionType = questionType;
		this.timeOut = timeOut;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "question_id", unique = true, nullable = false)
	public String getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(String questionId) {
		this.questionId = questionId;
	}
	
	@Column(name = "book_id")
	public String getBookId() {
		return bookId;
	}

	public void setBookId(String bookId) {
		this.bookId = bookId;
	}
	
	@Column(name = "create_time", length = 30)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "status", length = 11)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "content", length = 1000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "option_config", length = 500)
	public String getOptionConfig() {
		return this.optionConfig;
	}

	public void setOptionConfig(String optionConfig) {
		this.optionConfig = optionConfig;
	}

	@Column(name = "ans_val")
	public String getAnsVal() {
		return this.ansVal;
	}

	public void setAnsVal(String ansVal) {
		this.ansVal = ansVal;
	}

	@Column(name = "question_type", length = 11)
	public String getQuestionType() {
		return this.questionType;
	}

	public void setQuestionType(String questionType) {
		this.questionType = questionType;
	}

	@Column(name = "time_out", length = 20)
	public String getTimeOut() {
		return this.timeOut;
	}

	public void setTimeOut(String timeOut) {
		this.timeOut = timeOut;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
