package com.psy.entity;

// Generated 2015-6-9 11:07:24 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ReadRecord generated by hbm2java
 */
@Entity
@Table(name = "read_record")
public class ReadRecord implements java.io.Serializable {

	private String id;
	private String bookId;
	private String userId;
	private String type;
	private String score;
	private String content;
	private String bookName;
	private String bookImage;
	private String userName;
	private String userFace;
	private String createTime;
	private String beiyong1;
	private String beiyong2;
	private String reason;

	public ReadRecord() {
	}

	public ReadRecord(String bookId, String userId, String type,
			String score, String content, String userName, String userFace,
			String bookName, String bookImage, String createTime, 
			String beiyong1, String beiyong2, String reason) {
		this.bookId = bookId;
		this.userId = userId;
		this.type = type;
		this.score = score;
		this.content = content;
		this.userName = userName;
		this.userFace = userFace;
		this.bookName = bookName;
		this.bookImage = bookImage;
		this.createTime = createTime;
		this.beiyong1 = beiyong1;
		this.beiyong2 = beiyong2;
		this.reason = reason;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "book_id")
	public String getBookId() {
		return this.bookId;
	}

	public void setBookId(String bookId) {
		this.bookId = bookId;
	}

	@Column(name = "user_id")
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "score")
	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	@Column(name = "content", length = 2000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_face")
	public String getUserFace() {
		return this.userFace;
	}

	public void setUserFace(String userFace) {
		this.userFace = userFace;
	}

	@Column(name = "book_name")
	public String getBookName() {
		return bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	@Column(name = "book_image")
	public String getBookImage() {
		return bookImage;
	}

	public void setBookImage(String bookImage) {
		this.bookImage = bookImage;
	}
	
	@Column(name = "create_time", length = 30)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "beiyong1")
	public String getBeiyong1() {
		return this.beiyong1;
	}

	public void setBeiyong1(String beiyong1) {
		this.beiyong1 = beiyong1;
	}

	@Column(name = "beiyong2")
	public String getBeiyong2() {
		return this.beiyong2;
	}

	public void setBeiyong2(String beiyong2) {
		this.beiyong2 = beiyong2;
	}

	@Column(name = "reason")
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
